### PR TITLE
hook: fix insecure_ssl type and allow various hook config

### PR DESCRIPTION
**Pull request by samoht**
The insecure_ssl bits were changed in a7b4bd1b29ca15bb2d746a76ab694244a452c927
but it doesn't actually work. Also, there are many kind of config hooks
so allow to have a free-form assoc list to store the config values for these.

Note: it's probably not the right way to do that, but I haven't found a better one. Also, this needs more testing so please don't merge it yet.

### CODE REVIEW

**Comment by samoht** [comment]
I'm merging this as it seems to unlock https://github.com/docker/datakit/pull/243 but please feel free to revert/correct if you have a better fix.

/cc @mjambon or maybe it is possible to have default value/converter for `tag_field` but I haven't found it in the doc?

**Comment by mjambon** [comment]
Could you please post some sample input that illustrates the problem?
/cc @dsheets

**Comment by samoht** [comment]
The previous description was:

```
type hook_config = [
   | Web <json name="web"> of web_hook_config
 ]

type hook = {
  config <json tag_field="name">: hook_config;
  }
```

this parses `{ "name": "web"; "config": { ... }}` properly. However it fails with ``{ "name": "travis"; "config": { ... }}` and other `name` as this field is not fully specified by in the GitHub API (although `web` is). See https://developer.github.com/v3/repos/hooks/#create-a-hook

**Comment by mjambon** [comment]
I filed the request here: https://github.com/mjambon/atdgen/issues/54 but I don't expect to work on it personally anytime soon due to complexity and conflicting priorities in my schedule.

Your workaround is what I would have done in my application.

**Comment by dsheets** [comment]
I've addressed this in mjambon/atdgen#55.

**Pull request merged**
