### PR TITLE
Split data handling in its own package

### PR DESCRIPTION
**Pull request by emillon**
This exposes a dependency-light package for users that interact with the Github API through an HTTP client that is not cohttp (for example `curly`).

### CODE REVIEW

**Comment by avsm** [comment]
This looks good to me. What's left to turn it ready for review/merge?

**Comment by emillon** [comment]
@avsm I rebased it and it's now ready.

**Comment by emillon** [comment]
Re. 4.12 failures. Does the following plan make sense:
- locally disable the warning (so that we get meaningful CI)
- file an issue with 5.0.0 milestone documenting how to fix this
- when it's time to release 5.0.0, add a breaking change with a unit argument, and remove the warning override

**Comment by emillon** [comment]
Ah nevermind it's not public API. I'll open a PR for this.

**Comment by avsm** [comment]
Thanks!

**Pull request merged**
