### PR TITLE
#40

### PR DESCRIPTION
**Pull request by dinosaure**
This is the first output of my work. But we have a problem specifically with `ocaml-git`. Indeed, it's too much complex to functorize the handle of Git data with a subset of `ocaml-git`. The first commit describe this situation.

So, if you have a better approach, tell me.

PS: don't merge this PR, it's just to see my work and validate or not my approach.

### CODE REVIEW

**Comment by dsheets** [comment]
This looks like a good start.

I think the solution to the `ocaml-git` `IO` functor problem is to simply break top-level module compatibility and offer an `IO` module that is not a functor and has the same signature as the result of `ocaml-git`'s `IO` functor which does not refer to any component of the functor argument `D`. I believe this will also remove the dependency on `cstruct`.

**Comment by dinosaure** [comment]
I think we have a good compromise between complex signature of `ocaml-git` and an usable functor for `GitData`.

**Comment by samoht** [comment]
Simplification to ocamlgit signature are welcome!

**Comment by dinosaure** [comment]
May be it's useful to create a sub-module `Repo` inside `GitData` to get the [contents of git object](https://developer.github.com/v3/repos/contents/#get-contents) or functorize `Repo` module or another solution ?

At the moment, I create a new functor [RepoData] about this API but it's not final solution.

**Comment by dsheets** [comment]
I don't understand why `GitData` is so heavily functorized. Is it really possible to have 6 non-trivial dimensions to the result module? Doesn't GitHub serve the standard git data structures using well-known SHA hash and a single, straightforward object representation?

**Comment by dinosaure** [comment]
The problem is to keep the difference between type `Blob`, `Tree` and `Commit`. You can create 3 modules (`Blob`, `Tree` and `Commit`) according to the API that will be functorize with 2 argument (the object and SHA). The same type SHA for any objects (`ocaml-git` provides conversion functions) can also be considered - but we can not consider `Blob`, `Tree` and `Commit` as a same object (we could consider but the signature is too poor to treatments afterwards - like `Blob.to_raw`).

So we have these solutions:
* `Make (SHA: SHA) (Blob: BLOB) (Commit: Commit) (Tree: TREE)`
The user must make conversions on SHA.

* or
```
MakeBlob (SHA: SHA) (Blob: BLOB)
MakeCommit (SHA: SHA) (Commit: Commit)
MakeTree (SHA: SHA) (Tree: TREE)
```
Conversions on SHA are already made with this solution.

* or the current solution.

The last solution before this current is to copy the definition of common SHA  (like solution 1) with the conversions functions but the signature is too binding and huge to be interesting.

**Comment by dsheets** [comment]
Sorry, I still don't understand. Is there an actual use to have these module parameters? Will `SHA` ever be anything except the 'standard' SHA that GitHub uses? Do users really need to provide their own `Blob`, `Tree`, and `Commit` implementations?

Perhaps I was too flippant when I suggested `ocaml-github` compatibility -- given that we have a very specific service we are binding, it seems like we should be able to remove the functorization and only be compatible with the result signatures. Does that make sense? What have I missed?

**Comment by dinosaure** [comment]
My goal is to be consistent with `ocaml-git` without depend on it. In this sense, `ocaml-git` gives:

* A common SHA signing
* 3 SHA signatures Blob, and Commit Tree

The first question is: Do we use the common SHA (suggesting that the user - if he uses ocaml-git - converts the common SHA to the SHA Blob or Commit or Tree) or the user gives us 3 SHAs and we take care of these casts.

But we may well consider that `SHA.t = string`. In this case, it is compatible with `ocaml-git` but the user must make the cast.

ocaml-git also gives:

* Blob
* Commit
* Tree

They are incompatible. The user would like to create a new Blob for example. The second question is: should we manage the sending of a Blob coming directly from `ocaml-git` (and thus convert the blob to the expected JSON format - which means to we should know Blob by functorization) or the user needs to convert it into the record produced by ATD-gen.

We could just let the types produced by ATD-gen, and it's the user to convert his Blobs to our types.

I understand that goal with this sentence:

> It would be useful to look at the interfaces that ocaml-git exposes and attempt to expose interfaces that are at least partially compatible with those.

If you want just a low-level API and let a safe treatment for user, I can remove all functor. If you want a high-level API directly compatible with `ocaml-git`, we need to functorize or add dependence to `ocaml-git`

**Comment by dinosaure** [comment]
Also we can move the safe conversion function outside the API but they must be functorize for know how to convert record from ATD-gen to expected data.

**Comment by dsheets** [comment]
Ok, so you are proposing to use functors to avoid a dependency on `ocaml-git`. Users of the library would then supply their own implementations -- most likely from `ocaml-git`. Is that correct?

I see two other solutions which don't involve this functorization:

1. Factor common signatures from `ocaml-git` into `ocaml-git-types` on which `ocaml-git` and `ocaml-github` would then depend

2. Expose a low-level API in `ocaml-github` and then put the high-level `ocaml-git` compatible API in `ocaml-github-git` which would depend on `ocaml-git`.

These two approaches to dependency management represent two types of compatibility with `ocaml-git`:

1. A work-alike API that itself can be used as a functor parameter signature

2. A mix-n-match API that allows users to pass values between `ocaml-git` implementations and `ocaml-github` implementations.

I was initially suggesting approach 1 which can be done without factoring signatures into a new package and would instead rely on structural subtyping of result signatures but would not ensure compatibility at compile time.

You seem to be considering approach 2 which would require functorization or dependency. I agree that dependency is not acceptable which leaves us with functorization or something like `ocaml-github-git`. I don't see a use case for this mixing and matching between the libraries but perhaps one does exist and I simply haven't imagined it, yet. I do see a use case for approach 1 which is the ability to write code which works on local repositories identically to direct GitHub access. I think most of the applications of approach 2 may be better solved with an `ocaml-git` in-memory checkout from GitHub followed by regular pushes.

**Comment by samoht** [comment]
> I agree that dependency is not acceptable

any reason why? Again, I'm happy to make `ocaml-git` better/easier to depend-on if that helps.

**Comment by dinosaure** [comment]
Ok, you expect something like `OCaml_GIT(OCaml_GITHUB)` or `Git.FS(OCaml_GITHUB)`, right?

**Comment by dsheets** [comment]
Many uses of GitHub bindings care nothing about the actual data of git repositories and requiring an implementation of git for a REST API to GitHub seems excessive. There are these dependencies of `ocaml-git` that would be brought in: `mstruct` `dolog` `ocamlgraph` `crc`.

@samoht would you be willing to factor out common git signatures from `ocaml-git`? Or willing to parameterize over low-level git operations that `ocaml-github` could fulfill? Or both?

@dinosaure That is another option: figuring out a common signature that both a native git implementation and `ocaml-github`'s GitHub-based implementation could satisfy. This would be more invasive on `ocaml-git`, though, and would still benefit from factoring out common signatures. It would give `ocaml-git` users the option to use `ocaml-git`'s API against either implementation.

**Comment by samoht** [comment]
> would you be willing to factor out common git signatures from ocaml-git

It's already what `ocaml-git` is supposed to do. There are `ocaml-git.unix`, `ocaml-git.http` and `ocaml-git.mirage` if you want more complex implementation. But I'm not sure what you need/want exactly. Anyway I'm happy to change `ocaml-git` types and signatures to make them more generic if needed.

**Comment by dinosaure** [comment]
I think - but I'm not sure - @dsheets want to use `ocaml-git` with `ocaml-github` backend (I suppose is same as `ocaml-git.http` but specifically for GitHub API). My goal it's to use `ocaml-github` with `ocaml-git.{unix,mirage}` backend for this PR.

It's not a problem for me to follow to first or second approach. But we have (and it's this situation) a middle approach.

For the first approach (`ocaml-git` over `ocaml-github`), we have a problem: the ocaml GC. `ocaml-git` has an abstraction directly on the filesystem. GitHub doesn't provide a `loose` or `packed` object. If we have an abstraction over `loose` and `packed` object, it's possible to branch `ocaml-github` over (so we must respect an interface over that) and we can manipulate a git repository with `ocaml-git` by GitHub API.

For the second approach (the middle), we need a general abstraction of Git object and it must be the same between `ocaml-git` and `ocaml-github`. This abstraction will be `ocaml-git-types` and we can use that with `ocaml-git` or `ocaml-github`.

And the last approach it's (`ocaml-github` over `ocaml-git`) but I suspect it's not interesting for you. I don't know your goal and I have enough code to do what I wanted (get the files on GitHub). I can continue this PR but I want to be clear on the goal.

**Comment by dsheets** [comment]
My understanding was that `ocaml-git` implements the on-disk and wire formats for the git tool itself. @dinosaure's work on `ocaml-github` will create an alternative wire format and types that could be used in place of the types currently tied to the on-disk format. The compatibility between these two libraries should, IMO, be driven by a use case. The primary one to my mind is the ability to write code which is generic across these implementations but which is not necessarily format-compatible. This would make the format-specific parts of `ocaml-git` unnecessary to the extent that it seems either a package using both or a new package only exposing module signatures would be beneficial.

Perhaps simply adding `ocaml-git` as a dependency is the right way to go but that's not clear to me right now. Aside: one thing that `ocaml-github` could do to improve in its Mirage-compatibility that `ocaml-git` already does is use the nqsb TLS stack instead of the `ssl` package.

**Comment by yomimono** [comment]
I think this is unlikely to be merged in anything like the current form, given the huge amount of additional work @dinosaure has done since the original submission of this PR, and it looks like there hasn't been much discussion since 2015.  I'll close this for now, but if there's more to comment on, please feel free to re-open it.

**Pull request closed without merging**
