### PR TITLE
Properly expose github-jsoo and add missing dependencies

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Everything but the rename looks good. Shouldn't the module be `Github_jsoo`?

**Comment by samoht** [comment]
@rgrinberg I am trying to reflect what we do in `github-lwt`: I guess it's yet an other instance of the [linking trick](https://github.com/ocaml/dune/issues/136): `github.mli` is generated by the core lib and `lwt` as well as `jsoo` are implementing it for different backends.

**Comment by rgrinberg** [comment]
I see. So I guess this will need variants support to fully work.

**Comment by avsm** [comment]
varianttsssssssssssss

**Pull request merged**
