### PR TITLE
Initial support for Checks API.

### PR DESCRIPTION
**Pull request by tmcgilchrist**

### CODE REVIEW

**Comment by avsm** [comment]
Looks good to me (the TODO with the enum is fine to leave for now). Do you want to deploy this in ocurrent and then merge here once that's working?

**Comment by tmcgilchrist** [comment]
@avsm will do. 
I added the doc strings and links to the GitHub pages, and a small cli program to poke at the API.

**Comment by avsm** [comment]
CI should go green now if you rebase to the `master` branch

**Comment by avsm** [comment]
Thanks!

**Pull request merged**
