### PR TITLE
update OPAM file for 1.2 lint and new master repository location

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by dsheets** [comment]
These fail on opam-publish. I have patches for it and opam-sync-github-prs in the pipe.

**Comment by avsm** [comment]
ocaml/opam-repository#4015 has the upper bounds. Does REVDEPS skip uninstallable packages once that is merged, I wonder...

**Comment by dsheets** [comment]
I believe it should because these are direct dependencies. Transitive conflicts will require the Yorick-based ocaml-travisci-skeleton or something like it.

**Comment by dsheets** [comment]
This now fails due to ocaml/opam#2135.

**Comment by dsheets** [comment]
I've worked around the opam 1.2.1 issue in ocaml/ocaml-travisci-skeleton#38.

**Pull request merged**
