### PR TITLE
Sexp support

### PR DESCRIPTION
**Pull request by rgrinberg**
The most important benefit of this revision for me is that exceptions will now
be printed as sexp's whenever they aren't caught. Really makes debugging when
using this lib a lot easier.

@samoht please review the build system changes

cc @dsheets @avsm

We'll need wait for @mjambon to release atdgen before merging

### CODE REVIEW

**Comment by dsheets** [comment]
Does #116 solve your problem?

**Comment by rgrinberg** [comment]
@dsheets Yeah that is satisfactory. I'll close this PR if sexp converters aren't desirable.

**Comment by dsheets** [comment]
They may be useful but we can't merge this until atdgen gets updated. We're about to cut 1.1 so before atdgen's next publication, we'd like to have something useful. Also, `GITHUB_DEBUG=1` env var may help you.

**Comment by rgrinberg** [comment]
Atdgen is updated and released (1.9.0) with support for adding `[@@deriving ...]` converters btw.

**Comment by dsheets** [comment]
Oh! Is that sufficient for this purpose? Do you want sexp convertors on any other types or only the exceptions?

**Comment by rgrinberg** [comment]
I'd like to have sexp converters on all types but I don't want to write
the converters by hand myself. So if you're fine with the concerns
raised by @dbuenzli I'll update the PR for all types.

**Comment by dsheets** [comment]
That's fine with me. Feel free to update the PR. If you want it in 1.1, please do it in the next few hours. :-)

Thanks!

**Comment by samoht** [comment]
I am closing this as I am not sure this is needed anymore (and the code evolved quite a bit since then).

**Pull request closed without merging**
