### PR TITLE
[DO NOT MERGE] switch to topkg

### PR DESCRIPTION
**Pull request by samoht**
This is a partial translation to Topkg. I need to add the examples/binaries to complete it. The doc generation is also partly broken because ocamldoc complains that it cannot find the generated files. 

So need a little bit of work ...

### CODE REVIEW

**Comment by samoht** [comment]
Doc generation seems to be broken because of https://github.com/dbuenzli/topkg/issues/80

**Comment by dsheets** [comment]
What's the status of this?

**Comment by samoht** [comment]
The doc generation is blocked on a fix which needs to be done in topkg (/cc @dbuenzli). I still need to add the examples to `pkg/pkg.ml`.

**Comment by samoht** [comment]
Closing until the necessary changes are available in topkg.

**Pull request closed without merging**
